### ISSUE TITLE
Typo Fix

### ISSUE THREAD

**Issue by srimad-bhagavatam** [dwyl/learn-tdd#127]
What is TDD?
...
    How to Write Clean, Testable Code - http://youtu.be/XcT4yYu_TTs (ignore the Java code focus on the general principals)

# sed 's/principals/principles'

**Comment by nelsonic** [comment]
@srimad-bhagavatam you are 100% correct. 💯  
in this context `principals` should be `principles` ✍️ 
if you have time, please create a Pull Request with the change. 💻 
We would be very happy to merge it. :octocat:
