### ISSUE TITLE
Tweet Announcing Revised TDD Tutorial!

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-tdd#17]
No one has any excuse not to do Test Driven Development (TDD) in their Web App anymore!

**Comment by nelsonic** [comment]
Best time of day to announce is 17:00 GMT see: http://everytimezone.com/#2015-6-29,240,cn3

**Comment by nelsonic** [comment]
@iteles Please 
+ pick/find an appropriately click-worthy image
+ craft some great copy
+ tweet this tutorial
and paste the link to the tweet here. 
thanks! :+1:

**Comment by iteles** [comment]
I was looking around and my favourite image for TDD is either a photo of you working with a dwyl t-shirt or 
![tdd](http://www.schiffhauer.com/wp-content/uploads/2013/04/d1d5e9cc98c64375e99e35b1bab596e1.jpeg)

Which I now notice is in your tutorial! Do you have a preference?

**Comment by nelsonic** [comment]
For a complete beginner, the Red Green Refactor image means _**nothing**_.
It needs to be a funny image that tells a story.

**Comment by nelsonic** [comment]
https://twitter.com/dwylhq/status/621353373019865089
