### ISSUE TITLE
Istanbul Coverage Report Screenshot

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-tdd#21]
@iteles as requested:

<img width="574" alt="github-scraper-coverage-report" src="https://cloud.githubusercontent.com/assets/194400/9033681/4ab9b122-39c1-11e5-857c-92ef3db0647c.png">

Let me know if you need more detail/info.
Thanks! :heart:

**Comment by iteles** [comment]
Thank you! Using in github.com/dwyl/definition-of-done :heart:

**Comment by nelsonic** [comment]
Oh... ok. I will send you a better one once I've finished the scraper. :+1:

**Comment by iteles** [comment]
:+1: Placeholder.

**Comment by nelsonic** [comment]
<img width="576" alt="istanbul-coverage-nothing-ignored" src="https://cloud.githubusercontent.com/assets/194400/9034816/900079b0-39ca-11e5-89e7-e7aa3963e305.png">

**Comment by iteles** [comment]
:+1: Thanks again.
