### ISSUE TITLE
Readme.md in learn-tdd incorrect code under "Create the getChange function" 

### ISSUE THREAD

**Issue by sohilpandya** [dwyl/learn-tdd#33]
Hi @nelsonic, in the TDD tutorial when you are writing the **First Requirement** dummy test. you have some code under **"your index.html should now look like this:”** In here the test has a function without assert being the argument. 

So if one was to copy the code and then run the html file in the browser, it would fail with ReferenceError: assert is not defined.

**Comment by nelsonic** [comment]
Hi @sohilpandya can you reference the line number where this? (*thanks*)

**Comment by sohilpandya** [comment]
Not sure how to link the exact point. 

https://github.com/dwyl/learn-tdd/blob/master/README.md#create-the-getchange-function

Line 30 under the code in **"your index.html should now look like this:
"**

**Comment by nelsonic** [comment]
This one: https://github.com/dwyl/learn-tdd/blame/4b594c9b8d28b128aad09459127c99c562d08baa/README.md#L342 ?

**Comment by sohilpandya** [comment]
Yep in there - https://github.com/dwyl/learn-tdd/blame/4b594c9b8d28b128aad09459127c99c562d08baa/README.md#L374

this line.

**Comment by iteles** [comment]
_Aside: @sohilpandya, to reference a line number: https://github.com/dwyl/style-guide#issues_

**Comment by nelsonic** [comment]
Cool. good spot. 
<img width="897" alt="learn-tdd-assert-not-defined" src="https://cloud.githubusercontent.com/assets/194400/9982383/8d6d26ac-5fd2-11e5-82a8-bc9ee0645809.png">
please PR the fix. thanks! :+1:

**Comment by sohilpandya** [comment]
Thanks @iteles

**Comment by sohilpandya** [comment]
@nelsonic tried pushing change, permission was denied.

**Comment by nelsonic** [comment]
Did you Fork, Clone, Branch, Push, PR ?

**Comment by sohilpandya** [comment]
no, cloned the original, branched, pushed. 

will fork first.

**Comment by nelsonic** [comment]
@sohilpandya you fixed this, right? can we close the issue? :wink:

**Comment by sohilpandya** [comment]
:+1: Closed.
