### ISSUE TITLE
migrate to use codecov

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-tdd#39]
Codecov is *clearly* ***betterer*** than the *previous* coverage tracker...
@stevepeak wouldn't you *agree*...? :stuck_out_tongue_winking_eye:

**Comment by iteles** [comment]
:+1::+1:

We :heart: codecov!

![codecov](https://cloud.githubusercontent.com/assets/4185328/10920724/9eae90d6-8269-11e5-9ab4-708740eaaf0a.jpg)

**Comment by stevepeak** [comment]
:+1: Thank you @nelsonic and @iteles I do agree!
