### ISSUE TITLE
Sorry made commit by accident

### ISSUE THREAD

**Issue by andrewMacmurray** [dwyl/learn-tdd#47]
Sorry guys made a commit by accident to master (thought I was in a fork) :confounded: , will try and revert this.

**Comment by nelsonic** [comment]
*Ooops*... 
No worries, that's why we have version control. :wink: 
If you submit the changes as a Pull Request you will get feedback from others who have contributed to the tutorial and are thus watching it...
See in-line comments on your Commit: https://github.com/dwyl/learn-tdd/commit/f618217e2d9586577322ed0bab13387ad3aa2d1d

**Comment by andrewMacmurray** [comment]
@nelsonic thanks, hooray for version control! will submit a pr

**Comment by nelsonic** [comment]
Also, when we have PRs we can make sure that *Coverage* does not plummet: [![codecov.io](https://codecov.io/github/dwyl/learn-tdd/coverage.svg?branch=master)](https://codecov.io/github/dwyl/learn-tdd?branch=master) see: https://codecov.io/github/dwyl/learn-tdd?ref=f618217e2d9586577322ed0bab13387ad3aa2d1d

**Comment by andrewMacmurray** [comment]
@nelsonic thanks for the comments, we we're going through the tutorial trying not to look at too many hints (hence our tests aren't particularly descriptive and the JSDocumentation has disappeared!)

I made a branch called `revert-changes` where the files are at the previous commit but I can't seem to pr it (I feel like a bit of a klutz right now :disappointed: ), is there a proper way to revert back to the last commit? (don't want to mess things up again)

**Comment by naazy** [comment]
@andrewMacMurray look up git reset

**Comment by ryanpcmcquen** [comment]
I would recommend `git revert` instead of `reset`, since it won't require a forced push.

**Comment by andrewMacmurray** [comment]
@naazy @ryanpcmcquen thanks, have sorted it now and made a pr

**Comment by nelsonic** [comment]
@andrewMacmurray would you mind closing this issue now that its resolved? :-)

**Comment by andrewMacmurray** [comment]
@nelsonic sorry totally forgot
