### ISSUE TITLE
jsdoc installation not working (also I believe it is no longer supported)

### ISSUE THREAD

**Issue by interglobalmedia** [dwyl/learn-tdd#59]
Hi,

When I tried to install jsdoc by your instructions, it did not work. No html file was generated, and nothing happened when I tried to execute the subsequent commands. I believe that it has been replaced by jsdoc3. Please update this!

**Comment by indieforger** [comment]
Hi @interglobalmedia.

Please be more specific. Could you let us know what exactly doesn't work?
Which instruction step seems to be a problem? Also please copy and paste here error message you are getting.

Which version of `node` and `npm` are you using? You can chec it by executing following commands from the command line.
```
node -v
```
and 
```
npm -v
```

As described in the [guide](https://github.com/dwyl/learn-tdd#bonus-level-4-documentation-with-jsdoc-5-mins) producing documentation requires 3 steps:
> 1) Install jsdoc: `npm install jsdoc --save-dev`
> 2) Run the jsdoc command in your terminal: `./node_modules/jsdoc/jsdoc.js change.js`
> 3) Open the resulting html file open `./out/global.html#getChange` you should expect to see something like this in your web browser:

[dwyl/learn-tdd](https://github.com/dwyl/learn-tdd) is quite a comprehensive quide.
Installation of JSDOC, however, as described in step 1 is very straightforward.
You are using `npm` to install `jsdoc` package. I have just tried it locally and it appears to be fine.

Here is my output.
```
`-- jsdoc@3.4.0
  +-- async@1.4.2
  +-- bluebird@2.9.34
  +-- catharsis@0.8.8
  | `-- underscore-contrib@0.3.0
  |   `-- underscore@1.6.0
  +-- escape-string-regexp@1.0.5
  +-- espree@2.2.5
  +-- js2xmlparser@1.0.0
  +-- marked@0.3.6
  +-- requizzle@0.2.1
  | `-- underscore@1.6.0
  +-- strip-json-comments@1.0.4
  +-- taffydb@2.6.2
  +-- underscore@1.8.3
  `-- wrench@1.5.9
```

**Comment by indieforger** [comment]
Just saw issue #41. @interglobalmedia do you have nodeJS installed locally?

**Comment by interglobalmedia** [comment]
Do I have to fork this in order for it to work completely or can I start from scratch as I did? Everything works beautifully until JSDocs section. I finally got the out folder to be auto generated, but there was no global.html, only an index.html. The rest of the folder consists of a fonts folder, a scripts folder, and a styles folder. The installation was successful, it's just that what was installed did not seem right. Isn't there supposed to be a global.html file?

**Comment by interglobalmedia** [comment]
@indieforger I have npm installed locally. I believe I have Node installed locally but will check.

**Comment by interglobalmedia** [comment]
Yes, I do have Node installed locally. I also have npm installed locally.

**Comment by indieforger** [comment]
Hey @interglobalmedia. I was curious if it breaks so I did run all the steps, top to bottom. 
It worked perfectly fine. You don't have to fork the repository. It is just a guide.

And yes, you should get `global.html` generated for you in the `out` folder.

If everything else works fine no need to repeat all the steps. 

You could try to delete local `./out` folder and repeat all 3 steps.
1. First install jsdocs. Pay attention to the output to make sure you don't have errors there.
2. If successful run jsdoc parser as recommended and check `out` folder again.
```
$ ls -l ./out
```
You should get something like below.
```
total 24
-rw-r--r-- 1 IndieForger 197121 2521 Aug  4 23:53 change.js.html
drwxr-xr-x 1 IndieForger 197121    0 Aug  4 23:53 fonts/
-rw-r--r-- 1 IndieForger 197121 2192 Aug  4 23:53 global.html
-rw-r--r-- 1 IndieForger 197121 1029 Aug  4 23:53 index.html
drwxr-xr-x 1 IndieForger 197121    0 Aug  4 23:53 scripts/
drwxr-xr-x 1 IndieForger 197121    0 Aug  4 23:53 styles/
```
Again, please pay attention to errors if there are any. Pasting them here will make it easier to help you.
3. Before you check it the browser make sure you have have your static server running, simply run 
```
node static-server.js
```

PS. Nodemon is not required as we don't have to reload server when HTML changes. I have just opened #60 explaining why.

**Comment by interglobalmedia** [comment]
Hi @indieforger,

I deleted the out folder and repeated the three steps. Then I `ls -l ./out` and this is what I got:

`total 8
drwxr-xr-x  20 mariacam  staff  680 Aug  4 19:40 fonts
-rw-r--r--   1 mariacam  staff  945 Aug  4 19:40 index.html
drwxr-xr-x   4 mariacam  staff  136 Aug  4 19:40 scripts
drwxr-xr-x   5 mariacam  staff  170 Aug  4 19:40 styles`

Where could I have gone wrong in all this? Everything else previous to this worked fine. What could I have missed in the process?

**Comment by indieforger** [comment]
Hoestly I am running out of options here. I saw this repository only today so to make sure it all works fine I litterally followed all the steps A-Z. 

And honestly everything works perfectly fine for me.
Did you get any errors or warnings?

Also it might be good idea to ping @nelsonic as judging by the [contribution graph](https://github.com/dwyl/learn-tdd/graphs/contributors) he is the one who create the repository.

**Comment by interglobalmedia** [comment]
Hi @indieforger,

I figured it out. It was not clear that we were supposed to add the comments at the top of the change.js file. However, when I went into the new JSDocs website and followed their instructions (copied your comments), it worked. I suggest that you just clarify that part of the tutorial. Here is where I got my info: http://usejsdoc.org/about-getting-started.html Thanks!

**Comment by indieforger** [comment]
Great work! Well done!

**Comment by interglobalmedia** [comment]
Thanks! It was fun! I'm trying it out on a small project now. Should be interesting!
