### ISSUE TITLE
Nodemon is not required

### ISSUE THREAD

**Issue by indieforger** [dwyl/learn-tdd#60]
Nodemon is not required for running `static-server` as we don't have to reload server when HTML changes. Adding it introduces additional complexity into the guide. Perhaps we should drop it?

Everything will work just fine with running `node static-server.js`.
JSDoc and Istambul generate static HTML files, so refreshing browser is enough to see changes.

**Comment by interglobalmedia** [comment]
Hi @indieforder,

I am not even using static server. I use the atom's live server. Works for me just fine.

**Comment by nelsonic** [comment]
@indieforger the idea behind having `nodemon` is to let people _change_ the code and have the server serve up the new version of the file.

**Comment by nelsonic** [comment]
Remove `nodemon` and `hapi` (`static-server.js` and use https://github.com/tapio/live-server instead.

**Comment by indieforger** [comment]
> @indieforger the idea behind having nodemon is to let people change the code and have the server serve up the new version of the file. :recycle:

@nelsonic That is correct assuming that there are some server-side scripts you want to reload. If client html, js or css changes there is no need to reload the server as those files will be served upon browser refresh.

+1 for tapio/live-server. It is great tool.
