### ISSUE TITLE
Replace pit crew image with one that didn't cost their driver the championship

### ISSUE THREAD

**Issue by stevehopkinson** [dwyl/learn-tdd#65]
The photograph used to illustrate a 'consistent and beautifully illustrated team' shows the Ferrari F1 pit crew in 2008. Given that the pit crew cost Felipe Massa the championship that year by failing to remove the fuel hose from his car during a refuelling stop at the Singapore GP, it may be worth using an image of a different pit crew. Red Bull are a safe bet.

**Comment by iteles** [comment]
That's some decent F1 knowledge @stevehopkinson, thanks for raising the issue! 

If you have some time to drop us a PR to change it, that would be fantastic :blush:

**Comment by iteles** [comment]
@stevehopkinson Just so you're also aware: https://github.com/dwyl/contributing

**Comment by iteles** [comment]
You've done a lot of this already (and reading through it, I realise we need to simplify!) but you'll mostly be interested in:
https://github.com/dwyl/contributing#begin-work-on-the-technical-tasks
and
https://github.com/dwyl/contributing#pull-requests

**Comment by stevehopkinson** [comment]
Right, pull request set up now. Replace with a reliable, championship-winning Mercedes pit crew circa 2014.

PS Really hope the sense of humour came across there. I'm not actually Alan Partridge, honest.

**Comment by iteles** [comment]
@stevehopkinson It did, honestly, but I'm pretty stoked you will soon have contributor status on a repo with 237 stars and counting 😉 

Also, I kind of love that you took the time to raise an issue, it definitely made me laugh ❤️

**Comment by nelsonic** [comment]
@stevehopkinson are you a _bit_ of an `F1` ~~nerd~~ expert then...? 😉  ❤️ 
(_thanks for pointing this out! please help us find a bettererer image! preferably one on Flickr with creative commons license or if we have to pay for a stock photo or GIF just let us know...!_)

**Comment by nelsonic** [comment]
@stevehopkinson thanks for reporting & _fixing_ this! 👍
