### ISSUE TITLE
focus on "user story" as your requirement(s)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-tdd#68]
Came across https://github.com/jmonetti/tdd-for-humans today and slide `#10` reminded me that we don't have a _particularly_ good "_User Story_" in the Practical > Requirements section of this tutorial ... https://github.com/dwyl/learn-tdd#requirements we can do a _much_ better job of getting people in to the _habit_ of writing user stories ...

For reference this is the slide:
![user-stories-slide](https://cloud.githubusercontent.com/assets/194400/19658897/b0dc4b6a-9a21-11e6-8ea1-edda6777808b.png)

This format of slotting in the `Who`, `What` and `Why` makes it _very_ clear to people.

**Comment by emersonmellado** [comment]
PR open: https://github.com/dwyl/learn-tdd/pull/104

**Comment by iteles** [comment]
:tada: Thanks @emersonmellado !
