### ISSUE TITLE
Live Server (Confirm it works for a fresh install)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-tdd#69]
At present we are advising people to install `live-server`: https://github.com/dwyl/learn-tdd#live-server
but if they do not have a `package.json` in their working directory the `--save` will _fail_ and thus it will not start! we need to check this and add additional instructions as necessary...

**Comment by adeluccar** [comment]
Agreed. :+1:

**Comment by nelsonic** [comment]
addressed in: https://github.com/dwyl/learn-tdd/pull/97 🎉 
(_thanks again @kfern!_)
