### ISSUE TITLE
TDD in Ruby

### ISSUE THREAD

**Issue by pinglinh** [dwyl/learn-tdd#73]
Hi any plans for TTD in Ruby for beginners as well? 😄

**Comment by nelsonic** [comment]
@pinglinh great question! 
Yep the Ruby one existed _before_ the JS one... 
see: https://github.com/nelsonic/coin-change-ruby 👍

**Comment by pinglinh** [comment]
@nelsonic Awesome thank you!!! 🤓

**Comment by nelsonic** [comment]
We could _probably_ add a link to this in the readme in case someone `else` has this question...?

**Comment by pinglinh** [comment]
@nelsonic That's a great idea actually!
