### ISSUE TITLE
There is a small typo in the js code sample in README line 221

### ISSUE THREAD

**Issue by PiotrBerebecki** [dwyl/learn-tdd#77]
`var result = [1,2,3].indexOf(1);  // this should be 1`

should be

`var result = [1,2,3].indexOf(1);  // this should be 0`

**Comment by nelsonic** [comment]
@PiotrBerebecki thanks for reporting the typo. please PR a fix.

**Comment by bradreeder** [comment]
Thanks for raising issues @PiotrBerebecki 👍

**Comment by oliverjam** [comment]
I had the repo cloned already for another issue so I quickly fixed this typo (and another one that I really didn't want to raise a whole 'nother PR for, sorry!)
