### ISSUE TITLE
Outdated version of QUnit

### ISSUE THREAD

**Issue by RhodesPeter** [dwyl/learn-tdd#78]
According to the [QUnit documentation](https://api.qunitjs.com/QUnit.test/) the current way to run a test is like this:
```
QUnit.test('This sample test should always pass!', function(assert) {
        var result = 1 + 1;
        assert.equal(result, 2); // just so we know everything loaded ok
      });
```
As opposed to this:
```
 test('This sample test should always pass!', function(assert) {
        var result = 1 + 1;
        assert.equal(result, 2); // just so we know everything loaded ok
      });
```

Could we update the QUnit script from this (QUnit 1.18.0):
```
<link rel="stylesheet" href="https://code.jquery.com/qunit/qunit-1.18.0.css">
```
to this (QUnit 2.1.1):
```
<script src="https://code.jquery.com/qunit/qunit-2.1.1.js"></script>
```

The examples would also need to be changed.

**Comment by nelsonic** [comment]
@RhodesPeter I think the _reason_ QUnit is out-of-date was a "Blanket" compatibility issue, please confirm the latest QUnit works with the latest Blanket.js then update with a PR. thanks! 👍

**Comment by RhodesPeter** [comment]
#### Update:
- I can't find any documentation that clearly states the latest working version of QUnit for Blanket.js.
- The [example tests](https://github.com/alex-seville/blanket/blob/master/test/lib-tests/blanket_test.js) on the [blanket.js GitHub repo](https://github.com/alex-seville/blanket) use an older version of QUnit. 
- The QUnit version that Blanket.js is using hasn't been updated in 3 years, so I am fairly confident that compatibility is still an issue. ![qunit version updated](https://cloud.githubusercontent.com/assets/18164707/23361550/2502ea74-fce9-11e6-9305-2e26f99834ca.png)

Feel free to close the issue.

**Comment by nelsonic** [comment]
@RhodesPeter it might be _useful_ to add a _comment_ to the code informing _others_ why we are using an "_out-dated_" version of QUnit (_i.e. still worth a PR..._)

**Comment by RhodesPeter** [comment]
Ok no problem @nelsonic. I will put this together now 😀

**Comment by nelsonic** [comment]
Comment on version of QUnit added by @RhodesPeter 🎉 
closing. ✅
