### ISSUE TITLE
Istanbul command [README.md line 823] fails as Istanbul isn't installed globally

### ISSUE THREAD

**Issue by oliverjam** [dwyl/learn-tdd#79]
A few of us had trouble getting this to work this morning as we hadn't installed Istanbul globally. It might be worth changing the suggested command to `./node_modules/.bin/istanbul cover tests.js`. This would make it similar to the `live-server` command in the previous section.

I can create a PR if you're happy with the change?

**Comment by nelsonic** [comment]
@oliverjam thanks for fixing this. please close the issue when you are satisfied that it's working. 👍

**Comment by oliverjam** [comment]
Thanks for merging!
