### ISSUE TITLE
QUnit "enable coverage" not automatically ticked.

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/learn-tdd#82]
In the _**live server**_ section there needs to be a step letting you know that you need to tick the "Enable coverage" box as it is not ticked as default.

![box-ticking](https://cloud.githubusercontent.com/assets/21139983/23363963/0ebc35f2-fcf5-11e6-9e17-0730dfc4ec12.png)

Seems like a little thing but it stumped us for a frustrating amount of time!

**Comment by lucymonie** [comment]
Great issue @ZooeyMiller. I feel additional admiration because this stumped us last time and none of us raised an issue with dwyl about it. Self-head-smack

**Comment by nelsonic** [comment]
Pull Request informing people that ticking the coverage checkbox is required would be greatly appreciated. 😉

**Comment by ZooeyMiller** [comment]
@nelsonic good suggestion! Have just done so :)

**Comment by nelsonic** [comment]
@ZooeyMiller Thanks _very_ much for the PR! 🎉 
Please close the issue if you're happy that this is now clearer for the next people. 👍
